<?php
// $Id: panels_everywhere.module,v 1.7 2010/01/11 18:20:56 merlinofchaos Exp $

/**
 * @file panels_everywhere.module
 *
 * This module overrides the page theme to allow Panels to be used on all pages.
 */

/**
 * Implementation of hook_menu().
 */
function panels_everywhere_menu() {
  $items = array();

  $items['admin/build/panels/settings/everywhere'] = array(
    'title' => 'Everywhere',
    'file' => 'panels_everywhere.admin.inc',
    'page callback' => 'drupal_get_form',
    'access arguments' => array('administer page manager'),
    'page arguments' => array('panels_everywhere_settings_page'),
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Implementation of hook_theme()
 */
function panels_everywhere_theme() {
  $theme = array();
  $path = drupal_get_path('module', 'panels_everywhere') . '/theme';
  $base = array(
    'file' => 'theme.inc',
    'path' => $path,
  );
  $theme['pane_header'] = array(
    'arguments' => array(),
    'template' => 'pane-header',
  ) + $base;
  $theme['pane_messages'] = array(
    'arguments' => array(),
    'template' => 'pane-messages',
  ) + $base;
  $theme['pane_navigation'] = array(
    'arguments' => array(),
    'template' => 'pane-navigation',
  ) + $base;

  return $theme;
}

/**
 * Implementation of hook_ctools_plugin_directory()
 */
function panels_everywhere_ctools_plugin_directory($module, $plugin) {
  if ($module == 'page_manager' || $module == 'ctools') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implementation of hook_theme_registry_alter()
 *
 * This is the magic of this module, which allows us to completely override
 * how pages are output.
 */
function panels_everywhere_theme_registry_alter($registry) {
  if (variable_get('panels_everywhere_site_template_enabled', FALSE)) {
    // Test to see if we should exclude the administrative theme.
    if (!variable_get('panels_everywhere_site_template_enabled_admin', FALSE)) {
      global $theme;
      $admin_theme = variable_get('admin_theme', '0');
      if ($admin_theme && $admin_theme == $theme) {
        return;
      }
    }

    if (variable_get('panels_everywhere_override_page_tpl', FALSE)) {
      // If we've been set to override the page template, we completely override it:
      $registry['page']['template'] = 'page';
      $registry['page']['type'] = 'module';
      $registry['page']['path'] = drupal_get_path('module', 'panels_everywhere') . '/theme';
      $registry['page']['theme path'] = $registry['page']['path'];
      $registry['page']['theme paths'] = array(
        drupal_get_path('module', 'system'),
        $registry['page']['path'],
      );
      $registry['page']['preprocess functions'] = array(
        'panels_everywhere_page_preprocess',
        'template_preprocess',
        'template_preprocess_page',
        'ctools_preprocess_page',
      );
    }
    else {
      array_unshift($registry['page']['preprocess functions'], 'panels_everywhere_page_preprocess');
    }
  }
}

/**
 * Page preprocess to run the page content into our site template task.
 *
 * This is NOT named by the normal rules because this is not picked up
 * automatically. It is controlled by an alter so that it can come first.
 */
function panels_everywhere_page_preprocess(&$vars) {
  // For safety reasons, do not run this on the actual page configuration
  // pages and instead allow a more traditional output.
  if (strncmp($_GET['q'], 'admin/build/pages/edit', 21) == 0) {
    return;
  }
  if (strncmp($_GET['q'], 'admin/build/pages/nojs', 21) == 0) {
    return;
  }

  $task = page_manager_get_task('site_template');

  $content = new stdClass();
  $content->title = drupal_get_title();
  $content->content = $vars['content'];

  // Load the node into a context.
  ctools_include('context');
  ctools_include('context-task-handler');

  $page = page_manager_get_current_page();
  $contexts = ctools_context_handler_get_task_contexts($task, '', array($_GET['q'], $content, $page));

  // Since we're inside theme('page') we must call ctools_context_handler_render as though
  // we don't own the page, because crazy as it sounds, we don't.
  $info = ctools_context_handler_render($task, '', $contexts, array($_GET['q'], $content, $page), FALSE);
  if ($info && !empty($info['content'])) {
    // Because we run so early, we have to use drupal_set_title() and not
    // just set $vars['title']. Otherwise it will get overwritten.
    if (isset($info['title'])) {
      drupal_set_title($info['title']);
    }
    $vars['content'] = $info['content'];
    if (!empty($info['no_blocks'])) {
      $vars['show_blocks'] = FALSE;
    }
  }
}

/**
 * Implementation of hook_ctools_plugin_api().
 */
function panels_everywhere_ctools_plugin_api($module, $api) {
  if (variable_get('panels_everywhere_provide_sample', FALSE) && $module == 'page_manager' && $api == 'pages_default') {
    return array('version' => 1);
  }
}

/**
 * Drupal has a bug that causes theme file includes to get lost. However,
 * it is really convenient to have preprocess functions separated out
 * so that they 1) don't load code when unnecessary and 2) are easy to
 * find for non-developers.
 *
 * Until this bug http://drupal.org/node/591804 is fixed, we must have
 * this include.
 */
function panels_everywhere_init() {
  ctools_include('theme', 'panels_everywhere', 'theme');
}
