<?php
// $Id$

/**
 * @file pure_panels_template.module
 *
 * This module provides panel templates which are basically panels that can be
 * used within blocks or other panels.
 */

/**
 * Implementation of hook_perm().
 */
function pure_panels_template_perm() {
  return array('create panels template', 'administer panels template');
}

/**
 * Implementation of hook_menu().
 */
function pure_panels_template_menu() {
  // Safety: go away if CTools is not at an appropriate version.
  if (!defined('PANELS_REQUIRED_CTOOLS_API') || !module_invoke('ctools', 'api_version', PANELS_REQUIRED_CTOOLS_API)) {
    return array();
  }
  require_once drupal_get_path('module', 'pure_panels_template') . '/pure_panels_template.admin.inc';
  return _pure_panels_template_menu();
}

// ---------------------------------------------------------------------------
// Allow the rest of the system access to panel templates

/**
 * Statically store all used IDs to ensure all panel templates get a unique id.
 */
function pure_panels_template_get_id($name) {
  static $id_cache = array();

  $id = 'panel-template-' . $name;
  if (!empty($id_cache[$name])) {
    $id .= "-" . $id_cache[$name]++;
  }
  else {
    $id_cache[$name] = 1;
  }

  return $id;
}

// ---------------------------------------------------------------------------
// Database functions.

/**
 * Create a new page with defaults appropriately set from schema.
 */
function pure_panels_template_new() {
  ctools_include('export');
  return ctools_export_new_object('pure_panels_template');
}

/**
 * Load a single panel template.
 */
function pure_panels_template_load($name) {
  ctools_include('export');
  $result = ctools_export_load_object('pure_panels_template', 'names', array($name));
  if (isset($result[$name])) {
    if (empty($result[$name]->display)) {
      $result[$name]->display = panels_load_display($result[$name]->did);
    }
    /**
     * TODO: This is ugly as hell. Not sure if this is the best place to put this
     *
     */
    // Always default first context to the Node being viewed
    $result[$name]->contexts[0] = array(
      'name' => 'pure_panels_node',
      'id' => 1,
      'identifier' => t('Node being viewed'),
      'keyword' => 'node',
    );
    // Panel Everywhere Support
    $args = array(
      array(
        'keyword' => 'url',
        'identifier' => t('URL'),
        'id' => 1,
        'name' => 'string',
        'settings' => array(),
      ),
      array(
        'keyword' => 'content',
        'identifier' => t('Page content'),
        'id' => 1,
        'name' => 'page_content',
        'settings' => array(),
      ),
      array(
        'keyword' => 'page',
        'identifier' => t('Managed page'),
        'id' => 1,
        'name' => 'managed_page',
        'settings' => array(),
      ),
    );
    $result[$name]->arguments = $args + (array)$result[$name]->arguments;

    return $result[$name];
  }
}

/**
 * Load all panel templates.
 */
function pure_panels_template_load_all($reset=FALSE) {
  static $templates;

  // static cache
  if($templates && !$reset) {
    return $templates;
  }

  // If there's a cached version of the template_panels available, use it.
  if (!$reset && $cache = app_cache_get('pure_panels_template_load_all')) {
    $templates = $cache->data;
    return $templates;
  }

  ctools_include('export');
  $templates = ctools_export_load_object('pure_panels_template');
  $dids = array();
  foreach ($templates as $template) {
    if (!empty($template->did)) {
      $dids[$template->did] = $template->name;
    }
  }

  $displays = panels_load_displays(array_keys($dids));
  foreach ($displays as $did => $display) {
    $templates[$dids[$did]]->display = $display;
  }

  // Cache the template panels for later.
  app_cache_set('pure_panels_load_all', $templates, 'pure_panels_template');

  return $templates;
}

/**
 * Write a template panel to the database.
 */
function pure_panels_template_save(&$template) {
  if (!empty($template->display)) {
    $display = panels_save_display($template->display);
    $template->did = $display->did;
  }

  $update = (isset($template->pid) && $template->pid != 'new') ? array('pid') : array();
  drupal_write_record('pure_panels_template', $template, $update);

  // Clear the app cache for pure_panels
  app_cache_clear('pure_panels_load_all');

  return $template;
}

/**
 * Remove a panel template.
 */
function pure_panels_template_delete($template) {
  db_query("DELETE FROM {pure_panels_template} WHERE name = '%s'", $template->name);
  if ($template->type != t('Overridden')) {
    db_query("DELETE FROM {blocks} WHERE module = 'pure_panels_template' AND delta = '%s'", $template->name);
  }

  // Clear the app cache for pure_panels
  app_cache_clear('pure_panels_load_all');

  return panels_delete_display($template->did);
}

/**
 * Export a panel template.
 */
function pure_panels_template_export($template, $indent = '') {
  ctools_include('export');
  $output = ctools_export_object('pure_panels_template', $template, $indent);
  // Export the primary display
  $display = !empty($template->display) ? $template->display : panels_load_display($template->did);
  $output .= panels_export_display($display, $indent);
  $output .= $indent . '$template->display = $display' . ";\n";
  return $output;
}

/**
 * Remove the block version of panel templates from being available content types.
 */
function pure_panels_template_ctools_block_info($module, $delta, &$info) {
  $info = NULL;
}

/**
 * Menu callback to check to see if a template panel is valid as part
 * of a path, and if it is, return the template.
 */
function pure_panels_template_admin_load($name) {
  $template = pure_panels_template_load($name);
  if ($template && empty($template->disabled)) {
    return $template;
  }
}

/**
 * Implementation of hook_ctools_plugin_directory() to let the system know
 * we implement task and task_handler plugins.
 */
function pure_panels_template_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && $plugin == 'content_types') {
    return 'plugins/' . $plugin;
  }
}

function pure_panels_template_pure_panels_template_list() {
  $all_panels = pure_panels_template_load_all();
  $list = array();

  foreach ($all_panels as $name => $panel) {
    $list[$name] = check_plain($name) . ' (' . check_plain($panel->title) . ')';
  }
  return $list;
}
